version: '3'
services:
  app_prueba:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql_db:3306/prueba?useSSL=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      DB_USER_NAME: root
      DB_PASSWORD: root
    depends_on:
      mysql_db:
        condition: service_healthy
  mysql_db:
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: prueba
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
